### PR TITLE
Misc. TF-M+54L support

### PR DESCRIPTION
**Pull request by SebastianBoe**

### CODE REVIEW

**Comment by SebastianBoe** [comment]
I intend to make the toup's into fromlist when I have a green CI and review.

**Comment by mswarowsky** [comment]
`use uart30 instead of uart22 as the secure UART`

There is tag and a commit message body missing

**Review by mswarowsky — APPROVED** [review]
Assuming the commit message gets fixed, fine for me

**Comment by SebastianBoe** [comment]
reorganizing

**Pull request closed without merging**
