### PR TITLE
Upmerge 2021 07 26

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
revert list:

- ddf01ddb646f87ee3fd5a395b30ccb4595f570f6 [nrf fromlist] Platform: move inclusion of tfm_platform_system.c: merged upstream
- 13d81695a9cdec11febddff849908ed58911fb83 [nrf temphack]: Adding configurable BL2 config: conflicts with upstream and is marked temphack
- 885d345f84757e9940f3ed14b31348ac71c993f3 [nrf temphack]: Changing TFM config variables from PATH to STRING: conflicts with upstream and is marked temphack

Can the sdk fork maintainers please suggest more permanent fixes for the issues solved by the above temphacks that are now reverted?

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
> Can the sdk fork maintainers please suggest more permanent fixes for the issues solved by the above temphacks that are now reverted?

@oyvindronningstad ping

**Comment by mbolivar-nordic** [comment]
Also pinging @tejlmand since the relevant patches mentioned in the PR description are in the build system.

**Review by hakonfam — CHANGES_REQUESTED** [review]
NACK while working on a solution for the temphack with the STRING -> PATH change for the mbedtls config.

**Comment by mbolivar-nordic** [comment]
Thanks for taking that on @hakonfam .

**Comment by hakonfam** [comment]
https://github.com/nrfconnect/sdk-nrf/pull/5249 - not sure where to point my PRs at this time, so I just did it all on master to ensure that CI passes. There should be no conflicts.

**Comment by mbolivar-nordic** [comment]
> [nrfconnect/sdk-nrf#5249](https://github.com/nrfconnect/sdk-nrf/pull/5249) - not sure where to point my PRs at this time, so I just did it all on master to ensure that CI passes. There should be no conflicts.

I tried cherry-picking #28 onto this PR, but there are indeed conflicts:

```
$ git fetch origin pull/28/head
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 761 bytes | 108.00 KiB/s, done.
From https://github.com/nrfconnect/sdk-trusted-firmware-m
 * branch                refs/pull/28/head -> FETCH_HEAD
(west-dev) scarlet: ~/ncs/modules/tee/tfm (upmerge-2021-07-26) mbolivar
$ git cherry-pick FETCH_HEAD
Auto-merging trusted-firmware-m/config/config_default.cmake
CONFLICT (content): Merge conflict in trusted-firmware-m/config/config_default.cmake
error: could not apply 8cb12ee90... [nrf fromlist] Build: add internal option for configuring type of ...
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

**Comment by hakonfam** [comment]
> I tried cherry-picking #28 onto this PR, but there are indeed conflicts:

Sorry about that, need to learn not to trust my gut-feeling-based three way merge 😄 

I have made PRs against your upmerge branches now.

**Comment by hakonfam** [comment]
What is the reason for not updating `trusted-firmware-m` to the same upstream SHA as the zephyr module has? This upmerge updates to 9d93424a (https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/27/commits/71154320f41fc76611767edc346dd97463835641) while the zephyr module is on a199c304 (https://github.com/zephyrproject-rtos/trusted-firmware-m/commit/45bc61a3c7936540b91b646efa161c7b0f151352#diff-e33f485eb6fcbce940793884fe58d970d23a99c6c9a04c166275fb350a221589).

Some fixes introduced between these versions are needed for the several IPC tests to pass.

**Comment by mbolivar-nordic** [comment]
>  This upmerge updates to 9d93424a ([7115432](https://github.com/nrfconnect/sdk-trusted-firmware-m/commit/71154320f41fc76611767edc346dd97463835641)

Sorry, what do those SHAs have to do with this upmerge? I don't see either of those SHAs in this branch's recent history:

```
* f73454168 (HEAD -> upmerge-2021-07-26) [nrf fromlist] Build: add internal option for configuring type of ...
*   008f04796 (mbolivar-nordic/upmerge-2021-07-26) [nrf mergeup] Merge commit 'e18b7a9b040'
|\  
| * e18b7a9b0 trusted-firmware-m: platform: lpcxpresso55s69: Remove pull_drivers.cmake
```

> the zephyr module is on a199c304 (zephyrproject-rtos/trusted-firmware-m@45bc61a).

This upmerge generally speaking is bringing in Zephyr commit 14f09a3b00d49a453e9c3ecfa6c524bdd59679a9, which is what was HEAD in upstream's main branch when I got started. You can see the upstream manifest version for TF-M here:

https://github.com/zephyrproject-rtos/zephyr/blob/14f09a3b00d49a453e9c3ecfa6c524bdd59679a9/west.yml#L223

I.e. in upstream, TF-M was at version e18b7a9b0, which is what is being brought in by this upmerge PR.

**Comment by hakonfam** [comment]
> > This upmerge updates to 9d93424a ([7115432](https://github.com/nrfconnect/sdk-trusted-firmware-m/commit/71154320f41fc76611767edc346dd97463835641)
> 
> Sorry, what do those SHAs have to do with this upmerge? I don't see either of those SHAs in this branch's recent history:
> 

I was referring to upstream trusted-firmware-m commits.

> This upmerge generally speaking is bringing in Zephyr commit 14f09a3b00d49a453e9c3ecfa6c524bdd59679a9, which is what was HEAD in upstream's main branch when I got started. You can see the upstream manifest version for TF-M here:

I understand. I see now that you missed it the update we need with one day :D
https://github.com/zephyrproject-rtos/zephyr/commit/6a94b00d790fc42c370861589adb71b9375a258f

**Review by hakonfam — APPROVED** [review]
Both CI and manual testing passes with latest fix.

**Review by tejlmand — APPROVED** [review]
LGTM

**Pull request merged**
