### PR TITLE
platform: nordic_nrf: Add support for 54l

### PR DESCRIPTION
**Pull request by SebastianBoe**
Change-Id: I650ab5309cdea7f3508be7cfb124e0032c13d777

### CODE REVIEW

**Review by mswarowsky — APPROVED** [review]
Maybe we should stick with the commit tag scheme, but not very important for me

**Review by vili-nordic — APPROVED** [review]

**Review by SeppoTakalo — CHANGES_REQUESTED** [review]
I don't think we can accept !fixup commits. That may ruin someones rebase, if they have `autofixup` enabled.


Remove the tag.

**Comment by SebastianBoe** [comment]
@jfischer-no : We are re-writing the history before release right?

**Comment by SebastianBoe** [comment]
@SeppoTakalo : I don't think that scenario would happen before the history was rewritten, but I have updated accordingly.

**Review by SeppoTakalo — APPROVED** [review]

**Pull request merged**
