### PR TITLE
tf-m: move inclusion of tfm_platform_system.c to board

### PR DESCRIPTION
**Pull request by hakonfam**
... instead of SoC. This way out-of-tree platforms
can provide their own variant.

Ref: NCSDK-8453
Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

### CODE REVIEW

**Review by oyvindronningstad — APPROVED** [review]
Can you open an upstream PR as well?

**Comment by hakonfam** [comment]
> Can you open an upstream PR as well?

https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/9633 (Y)

**Review by ioannisg — APPROVED** [review]
Approving this, but let's wait until the upstream PR is sorted out - there seems to be a comment there.

**Comment by hakonfam** [comment]
Added DNM while waiting for upstream https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/9633

**Comment by ioannisg** [comment]
> Added DNM while waiting for upstream https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/9633

I think the upstream PR will be merged soon, so let's wait a bit more.

**Comment by ioannisg** [comment]
This is already merged upstream. Not sure if it could be fromtree, now. But it is not yet merged in the zephyr tfm module, so perhaps ok to leave it as is.

**Pull request merged**
