### PR TITLE
Upmerge 12 v2021

### PR DESCRIPTION
**Pull request by nvlsianpu**

### CODE REVIEW

**Comment by ioannisg** [comment]
I think this looks pretty straight forward. I only wonder if it would be better to revert first and then re-apply the temp-hack patches merged in #10

**Review by andvib — APPROVED** [review]
Passes CI

**Review by oyvindronningstad — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM

**Comment by ioannisg** [comment]
Good to go @nvlsianpu

**Pull request merged**
