### PR TITLE
[toup]: ITS: Fix header includes

### PR DESCRIPTION
**Pull request by mswarowsky**
fixup! [nrf toup]: ITS: Add support for encrypted ITS

The C++ style header was used, changed to C sytle.

Change-Id: Ic8fd152a4447d91f594cd85401e44236ccb3d1d4

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
[toup] -> [nrf toup]

**Review by jfischer-no — COMMENTED** [review]
There is confused "fixup! [nrf toup]: ITS: Add support for encrypted ITS" in the commit message.

**Comment by mswarowsky** [comment]
> There is confused "fixup! [nrf toup]: ITS: Add support for encrypted ITS" in the commit message.

I got told this is how we mark fixup commits in Zephyr, to give a hint that we can fixup this commit on the next TF-M upmerge

**Comment by jfischer-no** [comment]
> > There is confused "fixup! [nrf toup]: ITS: Add support for encrypted ITS" in the commit message.
> 
> I got told this is how we mark fixup commits in Zephyr, to give a hint that we can fixup this commit on the next TF-M upmerge

Could not find it, but see now it is current head.

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
